### ISSUE TITLE
License 问题

### ISSUE THREAD

**Issue by regymm** [hexuustc/fpgaol_compiling_server#1]
Hi, 最近我在基于这个代码搞新的编译服务器和类似的东西，这个项目虽然公开但好像还没有 License？是否可以加个 License 呢，比如比较 permissive 的 MIT License？

**Comment by hexuustc** [comment]
可以的，你如果方便的话就加一下吧，如果没空我加也可以

**Comment by regymm** [comment]
好的，已经加了。
目前我维护的版本（就是部署在学校服务器上的那个，后端加了 openxc7 和 symbiflow 支持）在 https://github.com/FPGAOL-CE/fpgaol-caas-backend ，如果需要可以合并回这里或者是 gitlab 之类的地方。
